
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "manager"
  config.vm.network "private_network", ip: "192.168.1.7"
  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
  end

end
