
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.1.8"
  config.vm.provision "shell", path: "provision.sh"

  # Configura o vbguest para não atualizar automaticamente
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
end
